import { Task } from './types';

export const CATEGORIES = [
  '📚 Learning',
  '📝 Assignments',
  '✍️ Writing',
  '💻 Coding Practice',
  '🏋️ Exercise',
  '📖 Reading',
  '🎯 Personal Goals',
  '🧪 Lab Work',
  '📊 Projects',
  '📅 Exams & Revision',
];

export const TEAM_MEMBERS = [
  {
    name: 'David Sanchez',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAraTcmdabOP6hOYivIYhbzFlHp9Tp3wiXPHjAeaYiQTYhE6t6XPxADxKTuly2x6mETbnj7sYb0t_n-sRKK350d35hEIQIpK1Vp5M5dh-zGB0tjgM9gEeKLynyiOu7Hi5tWzKgaKQm4XzpUhMkIjAhtNxrapbKikPsL6uAu_-iyZV5KKVjy0sju6F15nT_WJOHEoAvFxhDrLqpLahf_9bj2po7hqqi9bfLDwgcH2kdpK4Xsu5HGTpw6A8wftGH6l60Nqiw_gtXwoVg',
  },
  {
    name: 'Sarah Connor',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDgMI-d_uqXyj10nCgfeJRq-G3nWL-I3EJjYYtEHYCfSSuQajPN4HmVXZvP748ZRKuNsLPO0ttijQwsRhHQSJpNMfgWJwmuykaoaaqtbUireX2d6xnRX5yWvxQVz0y9zkaNB32oVP5aqQubu5M0Vz8DtBOjCFKWeDogGn1QZH84iK4mZ7KEs0RYvqDsYiuvzOav81xryOkxx0qwjgJFx469TS8QNJAYj71T7DJ2npfOVdtdIeV5I_B4uiUwTfPfH3jTY9lRObnf7k',
  },
  {
    name: 'Alex Mercer',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuABU6N4N3A865F-7sv-DagM4g--MFQdTwOeeuJ4ldjw00-nqkgKvUHKHB7p0Ag0aqZ2xHSXV_D5sbeyyvuaKIHI1SU6DpWCpeh1sK-H8kStQnvEynt2a38KXdzl5mFIyuZG4coIPpuM_K5wsp_AnY4dSeLv_TlTFiRrTCZKwWvsTZxAG8ggzB_ZADzg78EFshQwbDKknQe-XC9z76ozA0AfYecyOIEag95zUn9z4qjpLT34uHh7vGYkn-WeSaHzNkTbgI6udZeTNa0',
  },
  {
    name: 'Emily Watson',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCWbo_rxjFs0tz8Aiw1MvySgpC9faflOUyYZw3wJogTwDInPhbhBfbzN8v3kvJew7WtQy5BzQajTnIC0tk52E0WjCt1YmXJnHoyGu2429tD1bpqhL01Bo9kNHNaoStYHgND_fAB-a79xV5rvs6lFRboYYQzfMWUOI9U0cTJcfVzYJJCghHuBkfKPFZcAfsi7ygIIH3KH8xbi1-OWP33doh-p7myXzZrxNTU6Q4MOmIN8_ZfPIh3kZApbloaIEox_Si4qsuhJ6VRek',
  },
];

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const daysFrom = (n: number) => { const d = new Date(today); d.setDate(d.getDate() + n); return fmt(d); };

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Submit Data Structures Assignment',
    description: 'Complete all 5 problems from Chapter 4 and submit via the student portal.',
    priority: 'High',
    dueDate: daysFrom(1),
    startDate: fmt(today),
    startTime: '09:00',
    endTime: '11:00',
    category: '📝 Assignments',
    completed: false,
    progress: 60,
    reminder: true,
    reminderMinutes: 30,
    recurring: 'none',
    assignees: [TEAM_MEMBERS[0].avatar],
    assignedTo: ['David Sanchez'],
  },
  {
    id: 'task-2',
    title: 'Read Chapter 5 – Machine Learning',
    description: 'Focus on supervised vs unsupervised learning sections.',
    priority: 'Medium',
    dueDate: daysFrom(2),
    startDate: daysFrom(1),
    startTime: '14:00',
    endTime: '16:00',
    category: '📖 Reading',
    completed: false,
    progress: 20,
    reminder: false,
    recurring: 'none',
    assignees: [],
    assignedTo: ['David Sanchez'],
  },
  {
    id: 'task-3',
    title: 'Build React Portfolio Website',
    description: 'Create a personal portfolio with projects section and contact form.',
    priority: 'Medium',
    dueDate: daysFrom(5),
    startDate: daysFrom(0),
    startTime: '18:00',
    endTime: '20:00',
    category: '💻 Coding Practice',
    completed: false,
    progress: 35,
    reminder: true,
    reminderMinutes: 60,
    recurring: 'daily',
    assignees: [TEAM_MEMBERS[1].avatar, TEAM_MEMBERS[2].avatar],
    assignedTo: ['David Sanchez', 'Sarah Connor'],
  },
  {
    id: 'task-4',
    title: 'Revise Operating Systems Notes',
    description: 'Cover process scheduling, memory management, and deadlocks.',
    priority: 'High',
    dueDate: daysFrom(3),
    startDate: daysFrom(2),
    startTime: '10:00',
    endTime: '12:30',
    category: '📅 Exams & Revision',
    completed: false,
    progress: 10,
    reminder: true,
    reminderMinutes: 15,
    recurring: 'none',
    assignees: [],
    assignedTo: ['David Sanchez'],
  },
  {
    id: 'task-5',
    title: 'Morning Workout – Cardio + Strength',
    description: '30 min cardio + 30 min weight training. Track reps.',
    priority: 'Low',
    dueDate: daysFrom(0),
    startDate: daysFrom(0),
    startTime: '06:30',
    endTime: '07:30',
    category: '🏋️ Exercise',
    completed: false,
    progress: 0,
    reminder: true,
    reminderMinutes: 10,
    recurring: 'daily',
    assignees: [],
    assignedTo: ['David Sanchez'],
  },
  {
    id: 'task-6',
    title: 'Write Research Paper Introduction',
    description: 'Draft 500-word intro for the AI ethics paper. Cite at least 5 sources.',
    priority: 'High',
    dueDate: daysFrom(4),
    startDate: daysFrom(1),
    startTime: '15:00',
    endTime: '17:00',
    category: '✍️ Writing',
    completed: false,
    progress: 0,
    reminder: false,
    recurring: 'none',
    assignees: [],
    assignedTo: ['David Sanchez'],
  },
  {
    id: 'task-7',
    title: 'Chemistry Lab Report',
    description: 'Write up results from titration experiment. Include error analysis.',
    priority: 'Medium',
    dueDate: daysFrom(6),
    startDate: daysFrom(4),
    category: '🧪 Lab Work',
    completed: false,
    progress: 0,
    reminder: false,
    recurring: 'none',
    assignees: [TEAM_MEMBERS[3].avatar],
    assignedTo: ['David Sanchez', 'Emily Watson'],
  },
  {
    id: 'task-completed-1',
    title: 'Complete Python Basics Course',
    description: 'Finished all 8 modules on Coursera.',
    priority: 'Medium',
    dueDate: daysFrom(-3),
    category: '📚 Learning',
    completed: true,
    completedDate: daysFrom(-3),
    progress: 100,
    recurring: 'none',
    assignees: [],
    assignedTo: ['David Sanchez'],
  },
  {
    id: 'task-completed-2',
    title: 'Set Semester Goals',
    description: 'Wrote out 5 academic and 3 personal goals for this semester.',
    priority: 'Low',
    dueDate: daysFrom(-7),
    category: '🎯 Personal Goals',
    completed: true,
    completedDate: daysFrom(-7),
    progress: 100,
    recurring: 'none',
    assignees: [],
    assignedTo: ['David Sanchez'],
  },
  {
    id: 'task-completed-3',
    title: 'Group Project Planning Session',
    description: 'Planned milestones and assigned tasks among group members.',
    priority: 'High',
    dueDate: daysFrom(-5),
    category: '📊 Projects',
    completed: true,
    completedDate: daysFrom(-5),
    progress: 100,
    recurring: 'none',
    assignees: [TEAM_MEMBERS[1].avatar, TEAM_MEMBERS[2].avatar],
    assignedTo: ['David Sanchez', 'Sarah Connor', 'Alex Mercer'],
  },
];
